[tool.poetry]
name = "pythoneda-infrastructure-layer"
version = "0.0.1a1"
description = "Infrastructure laye for PythonEDA"
authors = ["rydnr <github@acm-sl.org>"]
readme = "README.md"
packages = [{include = "PythonEDAInfrastructure"}]

[tool.poetry.dependencies]
python = "^3.7"
pythoneda = "0.0.1a4"
requests = "^2.28.1"
grpcio = "^1.41.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
generate-grpc = "scripts.make_grpc:main"
